### ISSUE TITLE
Switch between view layouts

### ISSUE THREAD

**Issue by aylward** [KitwareMedical/VesselView#125] opened 2015-09-02 16:05 UTC
Pull-down menu with
1) 3D Only
2) Four-up View
3) Axial Slice
4) Coronal
5) Sagittal

In a toolbar above the panel on the left.

**Comment by jcfr** [comment] 2015-09-02 18:03
Looking at this could be useful:
* https://github.com/Slicer/Slicer/blob/91acaa06ac6b151c0b10438477225527e25c4348/Applications/SlicerApp/Resources/UI/qSlicerAppMainWindow.ui#L62-L95
* https://github.com/Slicer/Slicer/blob/91acaa06ac6b151c0b10438477225527e25c4348/Applications/SlicerApp/qSlicerAppMainWindow.cxx#L1385-L1403
* https://github.com/Slicer/Slicer/blob/91acaa06ac6b151c0b10438477225527e25c4348/Applications/SlicerApp/qSlicerAppMainWindow.cxx#L905-L908

**Comment by sumedhasingla** [comment] 2016-03-31 14:20
The issue is fixed in pull request: #135

**Closed** 2016-03-31 14:20 UTC
