### ISSUE TITLE
Edit Vessel module

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#77] opened 2015-01-27 21:18 UTC
Add a new module called Edit vessel. For now, it will allow user to remove a tube. It will use a mask input image that has the tube IDs. The user will be able to click in this image and select a tube (the tube should change color to appear selected). The user will then be able to click a button to remove the selected tube.

**Comment by jcfr** [comment] 2015-02-18 16:11
Duplicate of #86

**Closed by jcfr** 2015-02-18 16:11 UTC
Labels: enhancement
